In [1]:
!pip3 install torch torchvision

     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
      --------------------------------------- 0.1/5.7 MB 1.7 MB/s eta 0:00:04
     - -------------------------------------- 0.3/5.7 MB 2.6 MB/s eta 0:00:03
     -- ------------------------------------- 0.4/5.7 MB 2.9 MB/s eta 0:00:02
     --- ------------------------------------ 0.5/5.7 MB 3.0 MB/s eta 0:00:02
     ------ --------------------------------- 1.0/5.7 MB 4.1 MB/s eta 0:00:02
     -------- ------------------------------- 1.3/5.7 MB 4.4 MB/s eta 0:00:02
     ---------- ----------------------------- 1.5/5.7 MB 4.6 MB/s eta 0:00:01
     ------------ --------------------------- 1.8/5.7 MB 4.7 MB/s eta 0:00:01
     ------------- -------------------------- 2.0/5.7 MB 4.8 MB/s eta 0:00:01
     --------------- ------------------------ 2.3/5.7 MB 4.8 MB/s eta 0:00:01
     ---------------- ----------------------- 2.4/5.7 MB 4.7 MB/s eta 0:00:01
     ------------------ --------------------- 2.6/5.7 MB 4.6 MB/s eta 0

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [3]:
import random
import torch

In [7]:
A = torch.randint(100, size=(3,4,5)).type(torch.FloatTensor)/10
A

tensor([[[1.9000, 7.4000, 5.3000, 3.8000, 3.0000],
         [4.1000, 9.5000, 0.0000, 3.8000, 0.8000],
         [1.2000, 3.7000, 3.2000, 8.6000, 1.1000],
         [0.1000, 1.8000, 3.7000, 7.8000, 0.9000]],

        [[5.2000, 7.1000, 3.8000, 6.2000, 5.1000],
         [6.5000, 1.8000, 5.2000, 4.2000, 0.1000],
         [2.2000, 6.2000, 7.6000, 4.7000, 7.9000],
         [6.8000, 4.6000, 5.8000, 9.9000, 5.7000]],

        [[9.0000, 0.5000, 9.4000, 6.7000, 7.2000],
         [3.2000, 0.9000, 0.4000, 7.3000, 9.3000],
         [6.2000, 7.3000, 1.8000, 7.1000, 4.5000],
         [8.2000, 9.8000, 9.7000, 5.0000, 1.8000]]])

In [10]:
# Выведите его форму (shape)
A.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10

In [11]:
A.reshape(6,10)

tensor([[1.9000, 7.4000, 5.3000, 3.8000, 3.0000, 4.1000, 9.5000, 0.0000, 3.8000,
         0.8000],
        [1.2000, 3.7000, 3.2000, 8.6000, 1.1000, 0.1000, 1.8000, 3.7000, 7.8000,
         0.9000],
        [5.2000, 7.1000, 3.8000, 6.2000, 5.1000, 6.5000, 1.8000, 5.2000, 4.2000,
         0.1000],
        [2.2000, 6.2000, 7.6000, 4.7000, 7.9000, 6.8000, 4.6000, 5.8000, 9.9000,
         5.7000],
        [9.0000, 0.5000, 9.4000, 6.7000, 7.2000, 3.2000, 0.9000, 0.4000, 7.3000,
         9.3000],
        [6.2000, 7.3000, 1.8000, 7.1000, 4.5000, 8.2000, 9.8000, 9.7000, 5.0000,
         1.8000]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [57]:
vect = torch.tensor([1, 4, 2, 2, 1]).type(torch.FloatTensor)
A*vect, torch.mul(A, vect)

(tensor([[[ 1.9000, 29.6000, 10.6000,  7.6000,  3.0000],
          [ 4.1000, 38.0000,  0.0000,  7.6000,  0.8000],
          [ 1.2000, 14.8000,  6.4000, 17.2000,  1.1000],
          [ 0.1000,  7.2000,  7.4000, 15.6000,  0.9000]],
 
         [[ 5.2000, 28.4000,  7.6000, 12.4000,  5.1000],
          [ 6.5000,  7.2000, 10.4000,  8.4000,  0.1000],
          [ 2.2000, 24.8000, 15.2000,  9.4000,  7.9000],
          [ 6.8000, 18.4000, 11.6000, 19.8000,  5.7000]],
 
         [[ 9.0000,  2.0000, 18.8000, 13.4000,  7.2000],
          [ 3.2000,  3.6000,  0.8000, 14.6000,  9.3000],
          [ 6.2000, 29.2000,  3.6000, 14.2000,  4.5000],
          [ 8.2000, 39.2000, 19.4000, 10.0000,  1.8000]]]),
 tensor([[[ 1.9000, 29.6000, 10.6000,  7.6000,  3.0000],
          [ 4.1000, 38.0000,  0.0000,  7.6000,  0.8000],
          [ 1.2000, 14.8000,  6.4000, 17.2000,  1.1000],
          [ 0.1000,  7.2000,  7.4000, 15.6000,  0.9000]],
 
         [[ 5.2000, 28.4000,  7.6000, 12.4000,  5.1000],
          [ 6.5000,

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [66]:
A.shape

torch.Size([3, 4, 5])

In [ ]:
# тенхор A размерности [3, 4, 5] мы не сможим умнодить на себя что б получить размерность 6 на 6

In [64]:
B = A.reshape(6,10)

In [65]:
B@B.T

tensor([[232.0400, 130.4700, 181.2100, 245.6600, 174.5300, 262.9800],
        [130.4700, 179.1300, 159.5800, 211.7800, 177.0000, 201.1900],
        [181.2100, 159.5800, 246.5200, 278.5600, 220.4200, 300.4400],
        [245.6600, 211.7800, 278.5600, 417.0800, 336.2100, 358.3600],
        [174.5300, 177.0000, 220.4200, 336.2100, 417.3300, 248.5200],
        [262.9800, 201.1900, 300.4400, 358.3600, 248.5200, 451.2400]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [53]:
x = torch.tensor([1, 0.5, 2], requires_grad=True) # вектор точек
y = x**3 + x - 75*x
y.backward(x)

x.grad

tensor([ -71.0000,  -36.6250, -124.0000])

In [8]:
# Создайте единичный тензор размера 5x6

In [70]:
С = torch.ones(5,6)
С

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [71]:
# Переведите его в формат numpy

In [72]:
С.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [55]:
from torch.autograd import Variable


def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 100
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%10:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 11, x = 1.69, y = 4.12
Iteration 21, x = 1.55, y = 3.92
Iteration 31, x = 1.47, y = 3.85
Iteration 41, x = 1.42, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
